---
- include: init.yml
- hosts: app

  roles:
    - role: ansible-role-nginx
      nginx_user: "{{web_user}}"
      nginx_sites:
        default:
         - listen 80
         - server_name {{server_name}}
         - location / {
             proxy_pass http://107.170.230.178:8080;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection 'upgrade';
             proxy_set_header Host $host;
             proxy_cache_bypass $http_upgrade;
           }
